/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package professionalpractise;

import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author prathibha
 */
public class memonew3 extends javax.swing.JFrame {

    /**
     * Creates new form memonew3
     */
    int xmouse;
    int ymouse;
    
    Color s= new Color(51, 153, 255);
    
    public memonew3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose = new javax.swing.JLabel();
        lblGnum = new javax.swing.JLabel();
        lblInum = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setFont(new java.awt.Font("28 Days Later", 1, 24)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 30));

        lblGnum.setFont(new java.awt.Font("28 Days Later", 0, 50)); // NOI18N
        lblGnum.setText("GENERATE NUMBERS");
        lblGnum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblGnumMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGnumMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGnumMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGnumMouseEntered(evt);
            }
        });
        getContentPane().add(lblGnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        lblInum.setFont(new java.awt.Font("28 Days Later", 0, 50)); // NOI18N
        lblInum.setText("INPUT NUMBERS");
        lblInum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInumMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInumMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInumMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInumMouseEntered(evt);
            }
        });
        getContentPane().add(lblInum, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/newimg/mainmenu2.png"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblGnumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGnumMousePressed
        // TODO add your handling code here:
        lblGnum.setForeground(s);
    }//GEN-LAST:event_lblGnumMousePressed

    private void lblGnumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGnumMouseClicked
        // TODO add your handling code here:
        lblGnum.setForeground(s);
        patternS ps= new patternS();
        ps.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblGnumMouseClicked

    private void lblGnumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGnumMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblGnum.setForeground(Color.black);
    }//GEN-LAST:event_lblGnumMouseExited

    private void lblGnumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGnumMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblGnum.setForeground(Color.white);
    }//GEN-LAST:event_lblGnumMouseEntered

    private void lblInumMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInumMousePressed
        // TODO add your handling code here:
        lblInum.setForeground(s);
    }//GEN-LAST:event_lblInumMousePressed

    private void lblInumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInumMouseClicked
        // TODO add your handling code here:
        lblInum.setForeground(s);
        ShowPatterns sp = new ShowPatterns();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblInumMouseClicked

    private void lblInumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInumMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblInum.setForeground(Color.black);
    }//GEN-LAST:event_lblInumMouseExited

    private void lblInumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInumMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblInum.setForeground(Color.white);
    }//GEN-LAST:event_lblInumMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memonew3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memonew3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memonew3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memonew3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memonew3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblGnum;
    private javax.swing.JLabel lblInum;
    // End of variables declaration//GEN-END:variables
}
