/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package professionalpractise;

import java.awt.Color;
import java.awt.Cursor;



/**
 *
 * @author prathibha
 */
public class patternS extends javax.swing.JFrame {

    int xmouse;
    int ymouse;
    /**
     * Creates new form patternS
     */
    PatternGenerate pg=new PatternGenerate();
    public static String Q1 = memonew2.Q1;
    public static String Q2 = memonew2.Q2;
    public static String Q3 = memonew2.Q3;
    public static String Q4 = memonew2.Q4;
    public static String Q5 = memonew2.Q5;
        
    
    public patternS() {
        initComponents();
        lblcp.setVisible(false);
        lblp.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rten = new javax.swing.JRadioButton();
        rfive = new javax.swing.JRadioButton();
        label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblcp = new javax.swing.JLabel();
        lblp = new javax.swing.JLabel();
        lblback = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 23, 1000, 667));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 667));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rten);
        rten.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        rten.setForeground(new java.awt.Color(255, 255, 255));
        rten.setText("ABOVE TEN NUMBERS");
        getContentPane().add(rten, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        buttonGroup1.add(rfive);
        rfive.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        rfive.setForeground(new java.awt.Color(255, 255, 255));
        rfive.setText("BELOW TEN NUMBERS");
        getContentPane().add(rfive, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        label.setFont(new java.awt.Font("Avenir Next", 0, 16)); // NOI18N
        label.setForeground(new java.awt.Color(255, 255, 255));
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("NUMBER");
        label.setPreferredSize(new java.awt.Dimension(1000, 667));
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 100, 340));

        jLabel4.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Catogerized pattern");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 310, 30));

        jLabel5.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pattern");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 220, 30));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INFO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 310, 340));

        jLabel2.setFont(new java.awt.Font("Avenir Next", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPERATION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 240, 340));

        lblClose.setFont(new java.awt.Font("28 Days Later", 1, 24)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 30));

        lblcp.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblcp.setForeground(new java.awt.Color(153, 153, 153));
        lblcp.setText("Catogerized pattern");
        getContentPane().add(lblcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 55, -1, -1));

        lblp.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        lblp.setForeground(new java.awt.Color(153, 153, 153));
        lblp.setText("Pattern");
        getContentPane().add(lblp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 35, -1, -1));

        lblback.setFont(new java.awt.Font("Capture Smallz Clean", 0, 24)); // NOI18N
        lblback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblback.setText("BACK");
        lblback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbackMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbackMouseEntered(evt);
            }
        });
        getContentPane().add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 120, -1));

        lblStart.setFont(new java.awt.Font("Capture Smallz Clean", 0, 24)); // NOI18N
        lblStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStart.setText("PATTERN");
        lblStart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblStartMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStartMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStartMouseEntered(evt);
            }
        });
        getContentPane().add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 120, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/newimg/menu2.png"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblStartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMousePressed
        // TODO add your handling code here:
        lblStart.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblStartMousePressed

    private void lblStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseClicked
        // TODO add your handling code here:
        lblStart.setForeground(Color.LIGHT_GRAY);
        if (rten.isSelected()) {
            lblcp.setVisible(true);
            lblp.setVisible(true);
            int s1[] = pg.FillNumberCombinationArryAge(Q1);
            int s3[] = pg.FillNumberCombinationArryBirthDay(Q3);
            int s2[] = pg.FillNumberCombinationArryBirthMonth(Q2);
            int s4[] = pg.FillNumberCombinationArryFnumber(Q4);
            int s5[] = pg.FillNumberCombinationArryFmembers(Q5);
            String[] ss = pg.FinalpatternGenerate2(s1, s2, s3, s4, s5);
            String[] s = pg.FinalpatternGenerate(s1, s2, s3);
            String[] sp1 = pg.FinalpatternGenerate3(s1, s2, s3, s4, s5);
            String[] sp2 = pg.FinalpatternGenerate3(s1, s2, s3, s4, s5);

            label.setText(sp1[4] + sp2[4]);
            jLabel2.setText(sp1[6] + sp2[6]);
            jLabel1.setText(sp1[5] + sp2[5]);
            jLabel4.setText(sp1[0] + sp2[0]);
            jLabel5.setText(sp1[2] + sp2[2]);

        } else if (rfive.isSelected()) {
            lblcp.setVisible(true);
            lblp.setVisible(true);
            int s1[] = pg.FillNumberCombinationArryAge(Q1);
            int s3[] = pg.FillNumberCombinationArryBirthDay(Q3);
            int s2[] = pg.FillNumberCombinationArryBirthMonth(Q2);
            int s4[] = pg.FillNumberCombinationArryFnumber(Q4);
            int s5[] = pg.FillNumberCombinationArryFmembers(Q5);
            String[] ss = pg.FinalpatternGenerate2(s1, s2, s3, s4, s5);
            String[] s = pg.FinalpatternGenerate(s1, s2, s3);
            String[] sp1 = pg.FinalpatternGenerate3(s1, s2, s3, s4, s5);
            String[] sp2 = pg.FinalpatternGenerate3(s1, s2, s3, s4, s5);

            label.setText(sp1[4]);
            jLabel2.setText(sp1[6]);
            jLabel1.setText(sp1[5]);
            jLabel4.setText(sp1[0]);
            jLabel5.setText(sp1[2]);
        }else{
            MessageBox mb= new MessageBox("Select the lenght of the pattern", "Warning!");
            mb.setVisible(true);
            System.out.println("select first");
        }
    }//GEN-LAST:event_lblStartMouseClicked

    private void lblStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblStart.setForeground(Color.black);
    }//GEN-LAST:event_lblStartMouseExited

    private void lblStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblStart.setForeground(Color.white);
    }//GEN-LAST:event_lblStartMouseEntered

    private void lblbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMousePressed
        // TODO add your handling code here:
        lblback.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblbackMousePressed

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
        // TODO add your handling code here:
        lblback.setForeground(Color.LIGHT_GRAY);
        memonew3 mm3= new memonew3();
        this.dispose();
        mm3.setVisible(true);
    }//GEN-LAST:event_lblbackMouseClicked

    private void lblbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblback.setForeground(Color.black);
    }//GEN-LAST:event_lblbackMouseExited

    private void lblbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblback.setForeground(Color.white);
    }//GEN-LAST:event_lblbackMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patternS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patternS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patternS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patternS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patternS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblcp;
    private javax.swing.JLabel lblp;
    private javax.swing.JRadioButton rfive;
    private javax.swing.JRadioButton rten;
    // End of variables declaration//GEN-END:variables
}
