/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package professionalpractise;

import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;

/**
 *
 * @author prathibha
 */
public class ShowPatterns extends javax.swing.JFrame {
    int xmouse;
    int ymouse;
    
    public static String Q1 = memonew2.Q1;//age
    public static String Q2 = memonew2.Q2;//month
    public static String Q3 = memonew2.Q3;//day
    public static String Q4 = memonew2.Q4;//f number
    public static String Q5 = memonew2.Q5;// f memeber
    
    searchString ss= new searchString();
    
    ArrayList<String> fullinfo = new ArrayList<String>();
    /**
     * Creates new form ShowPatterns
     */
    public ShowPatterns() {
        
//        tfpattern.requestFocus();
        initComponents();
        lblage.setText(Q1);
        lblbm.setText(Q2);
        lblbd.setText(Q3);
        lblfn.setText(Q4);
        lblfm.setText(Q5);
        
        //aa=ss.Catogerize("123451234126");
        //ss.GivenSearch(aa);
        //jLabel2.setText("12345");
        //jTextArea1.setText(ss.GivenSearch2(aa));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStart = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblClose = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblfm = new javax.swing.JLabel();
        lblfmL = new javax.swing.JLabel();
        lblfn = new javax.swing.JLabel();
        lblfnL = new javax.swing.JLabel();
        lblbd = new javax.swing.JLabel();
        lblbdL = new javax.swing.JLabel();
        lblbm = new javax.swing.JLabel();
        lblbmL = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblageL = new javax.swing.JLabel();
        lblback = new javax.swing.JLabel();
        tfpattern = new javax.swing.JFormattedTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 667));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblStart.setFont(new java.awt.Font("28 Days Later", 0, 36)); // NOI18N
        lblStart.setText("Search");
        lblStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblStartMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStartMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblStartMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblStartMouseEntered(evt);
            }
        });
        getContentPane().add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(65, 65, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("           \n\n\n\n                                Enter your pattern and \n\t       click the search button \n");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 510, 290));

        lblClose.setFont(new java.awt.Font("28 Days Later", 1, 24)); // NOI18N
        lblClose.setText("X");
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 20, 30));

        jLabel3.setFont(new java.awt.Font("Avenir Next", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Pattern Here");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 65, -1, -1));

        jLabel1.setFont(new java.awt.Font("Avenir Next", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Your Info");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        lblfm.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblfm.setForeground(new java.awt.Color(255, 255, 255));
        lblfm.setText("Family Members:");
        getContentPane().add(lblfm, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 40, -1));

        lblfmL.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblfmL.setForeground(new java.awt.Color(255, 255, 255));
        lblfmL.setText("Family Members:");
        getContentPane().add(lblfmL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        lblfn.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblfn.setForeground(new java.awt.Color(255, 255, 255));
        lblfn.setText("Favourite Num:");
        getContentPane().add(lblfn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 270, 50, -1));

        lblfnL.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblfnL.setForeground(new java.awt.Color(255, 255, 255));
        lblfnL.setText("Favourite Num:");
        getContentPane().add(lblfnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        lblbd.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblbd.setForeground(new java.awt.Color(255, 255, 255));
        lblbd.setText("Birth Month:");
        getContentPane().add(lblbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, -1, -1));

        lblbdL.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblbdL.setForeground(new java.awt.Color(255, 255, 255));
        lblbdL.setText("Birth Day:");
        getContentPane().add(lblbdL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        lblbm.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblbm.setForeground(new java.awt.Color(255, 255, 255));
        lblbm.setText("Birth Month:");
        getContentPane().add(lblbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 40, -1));

        lblbmL.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblbmL.setForeground(new java.awt.Color(255, 255, 255));
        lblbmL.setText("Birth Month:");
        getContentPane().add(lblbmL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        lblage.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblage.setForeground(new java.awt.Color(255, 255, 255));
        lblage.setText("Age:");
        getContentPane().add(lblage, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, -1));

        lblageL.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        lblageL.setForeground(new java.awt.Color(255, 255, 255));
        lblageL.setText("Age:");
        getContentPane().add(lblageL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, -1, -1));

        lblback.setFont(new java.awt.Font("Capture Smallz Clean", 0, 24)); // NOI18N
        lblback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblback.setText("BACK");
        lblback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        lblback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbackMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblbackMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbackMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbackMouseEntered(evt);
            }
        });
        getContentPane().add(lblback, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 120, -1));

        tfpattern.setBackground(new java.awt.Color(51, 51, 51));
        tfpattern.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        tfpattern.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tfpattern.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfpattern.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfpattern.setFont(new java.awt.Font("Avenir Next", 0, 16)); // NOI18N
        getContentPane().add(tfpattern, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 200, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/professionalpractise/newimg/menu2.png"))); // NOI18N
        background.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroundMouseDragged(evt);
            }
        });
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroundMousePressed(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xmouse, y-ymouse);
    }//GEN-LAST:event_backgroundMouseDragged

    private void backgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMousePressed
        // TODO add your handling code here:
        xmouse = evt.getX();
        ymouse = evt.getY();
    }//GEN-LAST:event_backgroundMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        lblClose.setForeground(Color.LIGHT_GRAY);
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblClose.setForeground(Color.black);
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblClose.setForeground(Color.white);
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblStartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMousePressed
        // TODO add your handling code here:
        lblStart.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblStartMousePressed

    private void lblStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseClicked
        // TODO add your handling code here:
        lblStart.setForeground(Color.LIGHT_GRAY);
        fullinfo = ss.Catogerize(tfpattern.getText());
        jTextArea1.setText(ss.GivenSearch2(fullinfo));
    }//GEN-LAST:event_lblStartMouseClicked

    private void lblStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblStart.setForeground(Color.black);
    }//GEN-LAST:event_lblStartMouseExited

    private void lblStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblStart.setForeground(Color.white);
    }//GEN-LAST:event_lblStartMouseEntered

    private void lblbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMousePressed
        // TODO add your handling code here:
        lblback.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_lblbackMousePressed

    private void lblbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseClicked
        // TODO add your handling code here:
        lblback.setForeground(Color.LIGHT_GRAY);
        memonew3 mm3= new memonew3();
        this.dispose();
        mm3.setVisible(true);
    }//GEN-LAST:event_lblbackMouseClicked

    private void lblbackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseExited
        // TODO add your handling code here:
        setCursor(Cursor.DEFAULT_CURSOR);
        lblback.setForeground(Color.black);
    }//GEN-LAST:event_lblbackMouseExited

    private void lblbackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbackMouseEntered
        // TODO add your handling code here:
        setCursor(Cursor.HAND_CURSOR);
        lblback.setForeground(Color.white);
    }//GEN-LAST:event_lblbackMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowPatterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowPatterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowPatterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowPatterns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowPatterns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblageL;
    private javax.swing.JLabel lblback;
    private javax.swing.JLabel lblbd;
    private javax.swing.JLabel lblbdL;
    private javax.swing.JLabel lblbm;
    private javax.swing.JLabel lblbmL;
    private javax.swing.JLabel lblfm;
    private javax.swing.JLabel lblfmL;
    private javax.swing.JLabel lblfn;
    private javax.swing.JLabel lblfnL;
    private javax.swing.JFormattedTextField tfpattern;
    // End of variables declaration//GEN-END:variables
}
